<?php

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function layout_builder_ctools_plugin_directory($module, $plugin) {
	$plugins = array('display_renderers', 'layouts');

  if ($module == 'panels' && in_array($plugin, $plugins)) {
  	return 'plugins/' . $plugin;
  }

  if ($module == 'ctools' && $plugin == 'content_types') {
    return 'plugins/' . $plugin;
  }
}

function layout_builder_ctools_plugin_api($owner, $api) {
  if ($owner == 'panels' && $api == 'pipelines') {
    return array(
      'version' => 1,
      'path' => drupal_get_path('module', 'layout_builder') . '/includes',
    );
  }
}
